# The base image.
FROM python:3

# Python output is sent to terminal rather than get buffered.
ENV PYTHONUNBUFFERED=1

# Create a new folder if it does not exist.
WORKDIR /api

# Gives list of different packages that needs to be installed.
COPY requirements.txt ./

# Installs all the packages from requirements.txt.
RUN pip install -r requirements.txt